version: '3.8'

services:
  cronicle:
    image: soulteary/cronicle:latest
    ports:
      - "3012:3012"
    volumes:
      - cronicle-data:/opt/cronicle/data:rw
      - cronicle-logs:/opt/cronicle/logs:rw
      - cronicle-plugins:/opt/cronicle/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    hostname: cronicle
    restart: unless-stopped
    environment:
      - CRONICLE_base_app_url=http://localhost:3012

volumes:
  cronicle-data:
  cronicle-logs:
  cronicle-plugins: