version: '3.8'

services:
  cronicle:
    build:
      context: .
      dockerfile: Dockerfile
    image: cronicle-container
    ports:
      - "3012:3012"
    volumes:
      - cronicle-data:/opt/cronicle/data:rw
      - cronicle-logs:/opt/cronicle/logs:rw
      - cronicle-plugins:/opt/cronicle/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

volumes:
  cronicle-data:
  cronicle-logs:
  cronicle-plugins: